version: '3'
services: 
    admin:
        build: 
            context: .
            dockerfile: Dockerfile
        command: npm run start
        container_name: v_pay_admin
        ports:
            - "3001:3000"        
        volumes: 
            - ./:/frontend
            - /frontend/node_modules