services:
        mysql:
                container_name: mysql-onboard
                image: mysql/mysql-server:5.7.22
                restart: unless-stopped
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_ROOT_HOST: "%"
                ports:
                        - '3306:3306'
                volumes:
                        - ./mysql:/docker-entrypoint-initdb.d
                platform: linux/amd64

        zookeeper:
                container_name: zookeeper-onboard
                image: 'bitnami/zookeeper:latest'
                ports:
                        - '2181:2181'
                environment:
                        - ALLOW_ANONYMOUS_LOGIN=yes
                platform: linux/amd64

        kafka:
                container_name: kafka-onboard
                image: 'bitnami/kafka:latest'
                ports:
                        - '9092:9092'
                environment:
                        - KAFKA_BROKER_ID=1
                        - KAFKA_LISTENERS=PLAINTEXT://:9092
                        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
                        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
                        - ALLOW_PLAINTEXT_LISTENER=yes
                depends_on:
                        - zookeeper
                platform: linux/amd64